- name: Ensure required packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc 
    - python-setuptools 
    - python-devel 
    - postgresql-devel
    - git
    - python-pip
    - python-virtualenv






